name 'redmine'
maintainer 'Stanislav Bogatyrev'
maintainer_email 'realloc@realloc.spb.ru'
license 'Apache 2.0'
description 'Installs/Configures redmine'
long_description 'Installs/Configures redmine. Based on work by Alex Dergachev (alex@evolvingweb.ca)'
version '0.0.1'
supports 'debian', '>= 7.0'
depends 'tar', '>= 0.5.0'
depends 'mysql'
depends 'database'

